include(ExternalProject)

set(HYPRE_PREFIX_DIR ${CMAKE_CURRENT_BINARY_DIR}/hypre-build)
set(HYPRE_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/hypre)
set(HYPRE_CUDA_SM 70)
set(HYPRE_ENABLE_DEVICE_MALLOC_ASYNC OFF)

find_package(CUDAToolkit 11.0 REQUIRED)
if(CUDA_VERSION VERSION_GREATER_EQUAL 11.1.0)
  set(HYPRE_CUDA_SM 70 80)
endif()
if(CUDA_VERSION VERSION_GREATER_EQUAL 11.2.0)
  set(HYPRE_ENABLE_DEVICE_MALLOC_ASYNC ON)
endif()

ExternalProject_Add(HYPRE_DEVICE
  URL https://github.com/hypre-space/hypre/archive/refs/tags/v2.27.0.tar.gz
  SOURCE_SUBDIR "src"
  BUILD_ALWAYS ON
  CMAKE_CACHE_ARGS -DHYPRE_CUDA_SM:STRING=${HYPRE_CUDA_SM}
  CMAKE_ARGS -DHYPRE_ENABLE_SHARED=OFF
    -DHYPRE_WITH_MPI=OFF
    -DHYPRE_ENABLE_MIXEDINT=ON
    -DHYPRE_ENABLE_SINGLE=ON
    -DHYPRE_WITH_CUDA=ON
    -DHYPRE_WITH_GPU_AWARE_MPI=OFF
    -DHYPRE_ENABLE_CUSPARSE=ON
    -DHYPRE_ENABLE_DEVICE_MALLOC_ASYNC=${HYPRE_ENABLE_DEVICE_MALLOC_ASYNC}
    -DHYPRE_BUILD_TYPE=RelWithDebInfo
    -DHYPRE_INSTALL_PREFIX=${HYPRE_INSTALL_DIR}
    -DCMAKE_INSTALL_LIBDIR=${HYPRE_INSTALL_DIR}/lib
    -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DCMAKE_C_FLAGS_RELWITHDEBINFO=${CMAKE_C_FLAGS_RELWITHDEBINFO}
    -DCMAKE_CXX_FLAGS_RELWITHDEBINFO=${CMAKE_CXX_FLAGS_RELWITHDEBINFO}
    -DCMAKE_POSITION_INDEPENDENT_CODE=ON
    -DCMAKE_C_VISIBILITY_PRESET=hidden
    -DCMAKE_CXX_VISIBILITY_PRESET=hidden
    -DCMAKE_CUDA_VISIBILITY_PRESET=hidden
    -DCMAKE_ENABLE_EXPORTS=TRUE
    -DCMAKE_CUDA_HOST_COMPILER=${CMAKE_CXX_COMPILER}
)

add_dependencies(cholbench HYPRE_DEVICE)
target_link_libraries(cholbench PRIVATE ${HYPRE_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}HYPRE.a
  CUDA::cudart CUDA::curand CUDA::cublas CUDA::cusparse CUDA::cusolver) 
target_include_directories(cholbench PRIVATE ${HYPRE_INSTALL_DIR}/include)
